# Generated by Django 3.0.4 on 2020-03-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200314_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(upload_to='store/media/images/'),
        ),
    ]
